name: Push to Amazon ECR
author: jwalton
description: Push a docker image to (or pull from) Amazon ECR.
inputs:
  access-key-id:
    description: Access key for IAM User.
  secret-access-key:
    description: Secret access key for IAM User.
  image:
    description: The name of the image on ECR.
  local-image:
    description: The local name of the image.  If not specified, defaults to same as 'image'.
    required: false
  region:
    description: AWS Region to use.  Defaults to us-east-1.
    required: false
  direction:
    description: Whether to "push" or "pull" the image. Defaults to "push".
    required: false
  is-semver:
    description: Specifies if the image follows the semantic versioning standard. It will push X, X.Y and X.Y.Z tags. Defaults to false.
    required: false
    defaults: false
  remote-image-tags: 
    description: A comma separated list (or single entry) of remote tags to be pushed
    required: true
runs:
  using: node12
  main: 'main.js'
branding:
  icon: upload
  color: orange
